name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload build artifact
      if: success() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: spellbook-plugin
        path: target/Spellbook-*.jar
        if-no-files-found: error
